# Dependencies
markdown:         redcarpet
rogue:         	  true

# Permalinks
permalink:        pretty

# Setup
title:            Jordan Clifton Blog
tagline:          Technical to Personal
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Jordan Clifton
  url:            https://twitter.com/Jordan_Clifton
  email:          jfc1254@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jfclifton/JordanBlog
